### ISSUE TITLE
Agent Self throwing HTTP 503.

### ISSUE THREAD

**Issue by nandhusriram** [OrbitzWorldwide/consul-client#101]
I have a method that performs periodic health check , in that method I am getting agent/self call and it throws 503.

	Agent agentSelf = consul.agentClient().getAgent();
		
			ConsulResponse<Map<String,List<String>>> services = consul
					.catalogClient().getServices(QueryOptions.BLANK);
			builder.up().withDetail("services", services.getResponse());
					.withDetail("agent", agentSelf);

**Comment by nandhusriram** [comment]
More information

Exception [EclipseLink-34] (Eclipse Persistence Services - 2.6.0.v20150309-bf26070): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: This class does not define a public default constructor, or the constructor raised an exception.
Internal Exception: java.lang.InstantiationException
Descriptor: XMLDescriptor(com.orbitz.consul.model.agent.Agent --> [])

I could see the response like this InboundJaxrsResponse{context=ClientResponse{method=GET, uri=http://hostname:8500/v1/agent/self, status=200, reason=OK}}

**Comment by rickfast** [comment]
Are you using Jersey? If so, is ```jersey-media-json-jackson``` on the classpath?

```xml
<dependency>
	<groupId>org.glassfish.jersey.media</groupId>
	<artifactId>jersey-media-json-jackson</artifactId>
	<version>2.22.2</version>
</dependency>

```

**Comment by nandhusriram** [comment]
Worked , thanks

**Comment by rickfast** [comment]
np. i'll update the README with instructions for jersey
