### ISSUE TITLE
Support to specify a service-specific IP address

### ISSUE THREAD

**Issue by FraBle** [OrbitzWorldwide/consul-client#106]
I'm running several docker containers. One is used for [Consul](https://hub.docker.com/r/voxxit/consul/), running server and agent on the same machine. Another one is used for a Java service (Dropwizard) using the Java Docker image. To connect my Java service with Consul, I use [dropwizard-consul](https://github.com/smoketurner/dropwizard-consul). It is based on consul-client.

Since the Java container has its own IP address, but does not propagate it to Consul as service address, I don't have a valid service registration.
Consul uses the agents address as fallback, which is wrong in my case.

However, it's possible to specify a service address:

> The address field can be used to specify a service-specific IP address. By default, the IP address of the agent is used, and this does not need to be provided.

(duplicate of #28, but it has never been reconsidered yet)

**Comment by gjesse** [comment]
You can already do this, though it's a little indirect. Something like

```java
        Registration.RegCheck check = Registration.RegCheck.http("http://check/path", 10);
        
        Registration registration = ImmutableRegistration
                .builder()
                .port(1234)
                .address("192.168.0.24")
                .check(check)
                .name("name")
                .id("id")
                .addTags("tag", "tag2")
                .build();
                
        client.agentClient().register(registration);
```

I think the general use case is that people run the agent locally on the machine, so I'm guessing this is not a very common use case, and therefore probably not worth adding another set of overloaded registration methods to `AgentClient`

**Comment by rickfast** [comment]
I'm inclined to agree. There's already more ```register``` methods than I'd like. Going to close this for now.

**Comment by FraBle** [comment]
I took @gjesse advice and added the missing functionality to [smoketurner/dropwizard-consul](https://github.com/smoketurner/dropwizard-consul) ([Pull Request](https://github.com/smoketurner/dropwizard-consul/pull/4)). Thank you!
