### ISSUE TITLE
KVCache will truncate keys in the key map

### ISSUE THREAD

**Issue by Sahasrara** [OrbitzWorldwide/consul-client#110]
final Function<Value, String> keyExtractor = new Function<Value, String>() {
            @Override
            public String apply(Value input) {
                return input.getKey().substring(rootPath.length() + 1); **<---**
            }
        };

This guy needs to be changed so that it doesn't truncate key names.  It might be cool if it ignored trailing slashes.  Maybe something like this, but less dumb:

Set<String> incomingKey = new HashSet(Arrays.asList(input.getKey().split("/")));
Set<String> rootKey = new HashSet(Arrays.asList(rootPath.split("/")));
incomingKey.removeAll(rootKey);
return incomingKey.iterator().next();

**Comment by rickfast** [comment]
I'll fix this this week.

**Comment by Sahasrara** [comment]
thanks!

**Comment by rickfast** [comment]
Fixed by 9f429800d2093826ee9d40df7c73fd74bf860bc9

**Comment by Sahasrara** [comment]
Dope, thanks!
