### ISSUE TITLE
Fix for intelli-j generated sources

### ISSUE THREAD

**Issue by bkrahmer** [OrbitzWorldwide/consul-client#111]
At the bottom of the page there are workarounds described for working with intelli-j.  Something similar to this at the bottom of your build.gradle will fix it:

sourceSets {
    main {
        java.srcDirs += "${buildDir}/generated/source/proto/main/java/"
    }
    test {
        java.srcDirs += "${buildDir}/generated/source/proto/test/java/"
    }
}

cheers,
brian

**Comment by rickfast** [comment]
boom aefdf0518a5965607ed90405ccdd6041c4d40323
