### ISSUE TITLE
health check is problem !

### ISSUE THREAD

**Issue by yeyincai** [OrbitzWorldwide/consul-client#113]
service register consul   and add  check healthurl ,but   runtime   look  tcp  client ,too  many  port  on TIME_WAIT state ,that is bug?

**Comment by rickfast** [comment]
Consul client doesn't actually perform the health checks. The agent does that. The client just tells the agent how to monitor the registered application. Sounds like a problem with your health check?

**Comment by yeyincai** [comment]
Maybe  health   checks  url has  problem
