### ISSUE TITLE
Shaded packages

### ISSUE THREAD

**Issue by lburgazzoli** [OrbitzWorldwide/consul-client#118]
In the latest version almost all the dependencies are shaded inside the jar and I'm wondering if it could be better to hide all the shaded packages from the end user I mean, as example, it is possibility to tweak Jackson object mapper but if I want to add a module, it has to be compatible with the shaded version but that could break the isolation. Another problem is using the shaded package in osgi as if shaded packages are also used in API, they have to be exported that could leat to potentially export all the packages (not a big deal but not the best)

Make sense ?

**Comment by rickfast** [comment]
Yeah I get it. I'll unshade Jackson and Guava, but I'll leave the HTTP stuff in the JAR.

**Comment by lburgazzoli** [comment]
Great, thx for the fast answer

**Comment by lburgazzoli** [comment]
btw, would you like me to work on that while working on OSGi stuffs ?

**Comment by rickfast** [comment]
yes - i just pushed the unshading of jackson and guava. can you make the appropriate OSGi updates?

**Comment by lburgazzoli** [comment]
Would it be possible to have a minor release ? 
So I can work on the osgi bundle on ServiceMix so that your jar won't be touched and OSGi problems can be avoided ?

**Comment by rickfast** [comment]
Not sure what you mean?

**Comment by lburgazzoli** [comment]
Not really clear indeed.

Unfortunately making  maven-shade-plugin and maven-bundle-plugin working together is not really trivial and it is really error-prone and that sometimes leads to issues so one of the possible solutions is to re-package your jar as OSGi bundle as part of ServiceMix bundles colelction (https://github.com/apache/servicemix-bundles).

This has the advantage that your jar is untouched so you do not need to worry about OSGi anymore at least for the packaging stuffs, the side-effect is that someone has to take care of making such bundle (I already did it).

If I'll find a way to easily add OSGi support I'll get back with a PR but for the time being the ServiceMix bundle is more than enough for my needs.

**Comment by rickfast** [comment]
Cool. I'll close this for now then
