### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by nandhusriram** [OrbitzWorldwide/consul-client#12]
How to register with hostname address, I do see only options to set port ?

**Comment by rickfast** [comment]
The hostname is typically provided by the locally running Consul agent.  Are you trying to register with a remote Consul server?

**Comment by nandhusriram** [comment]
I am trying to register a both local and remote  restful service to  locally running consul agent  .

**Comment by rickfast** [comment]
Ah.  I will add Address to the Registration class this week and release a new version. That will allow you to specify a specific host name or IP address.

**Comment by nandhusriram** [comment]
Thanks

**Comment by rickfast** [comment]
I've added ```Address``` to the ```Registration``` object.  To register a remote service with the local agent use ```AgentClient.register(Registration registration)```

**Comment by rickfast** [comment]
Will release 0.8.3 today
