### ISSUE TITLE
Values in KV surrounded by quotation marks

### ISSUE THREAD

**Issue by michalkalinowski** [OrbitzWorldwide/consul-client#123]
For some reason, all values that are put by ```KeyValueClient``` are surrounded by quotation marks.

When inserting like this:
```curl -X PUT -d 'test' http://192.168.99.100:8500/v1/kv/key```
the actual value is ```test```.

When inserting like this:
```kvClient.putValue("key", "test");```
the actual value is ```"test"```.

It is OK if the only Consul's KV clients ale Java apps using this lib, but in general this behaviour is quite weird I believe.

**Comment by rickfast** [comment]
Yeah. It's a problem with the new HTTP client thatWe swapped in. Use 0.10.2 for the time being. I'll fix this today

**Comment by michalkalinowski** [comment]
OK, great! It it's not an issue for you, please publish this fixed version to Maven Central. Thanks!

**Comment by rickfast** [comment]
Sure. I fixed it on the train just now. I'll merge and release shortly.

**Comment by rickfast** [comment]
`0.11.3` is released. Retrofit was using the JSON converter to handle string request bodies, so they were turned into JSON strings (with quotes). I changed the String payload calls to use the plain text string converter.
