### ISSUE TITLE
encoding issue

### ISSUE THREAD

**Issue by bprager** [OrbitzWorldwide/consul-client#124]
I am trying to store and retrieve serialized objects (byte-arrays) in Consul.
In the following test-code the retrieved byte-array is different than the stored one, which suggests an encoding issue in the client:
```
		TestClass testObject = new TestClass();
		Object clone = SerializationUtils.clone((Serializable) testObject);
		byte[] serializedTestObject = SerializationUtils.serialize((Serializable) clone);
		
		// write test object to registry
		logger.info("write: '" + serializedTestObject + "'.");
		kvClient.putValue(key, new String(serializedTestObject));
		// read test object from registry
		returnedValueAsString = kvClient.getValueAsString(key);
		returnedObjectAsString = returnedValueAsString.get();
		logger.info("returned: '" + returnedObjectAsString);
		if (!serializedTestObject.equals(returnedObjectAsString.getBytes())) {
			logger.error("something went wrong: we got a different result");
		}
		try {
			Object finalResult = SerializationUtils.deserialize(returnedObjectAsString.getBytes());
			logger.info("yielded in: '" + finalResult + "'.");

		} catch (Exception e) {
			logger.error("Failed with: " + e.getMessage());
		}
```
(@rickfast was able to confirm the existing issue so far.)
Thank you for looking into it.

**Comment by odiszapc** [comment]
@bprager could you please provide a complete code snippet?

**Comment by odiszapc** [comment]
It's a Consul base64 decoding issue. Consider using of base64 pre-encoded strings to save binary streams into KV store. I guess this issue can not be fixed in this library.
Looks like Base64 encoding of binary arrays in Go incompatible with consequest decoding in Java.
But `new String(bytesFromConsul)` is OK.
