### ISSUE TITLE
Shadow jar as one of the options

### ISSUE THREAD

**Issue by SerCeMan** [OrbitzWorldwide/consul-client#128]
Please provide the shadow jar as one of the artifacts available on Bintray. Jackson has a lot of conflicts with other libraries.

**Comment by rickfast** [comment]
I will try and get to this sometime this week. Thanks

**Comment by rickfast** [comment]
```xml
<dependency>
        <groupId>com.orbitz.consul</groupId>
        <artifactId>consul-client</artifactId>
        <version>0.12.0</version>
        <classifier>all</classifier>
    </dependency>
```

Fixed

**Comment by SerCeMan** [comment]
Thank you :+1:

**Comment by rickfast** [comment]
Looks like the shaded JAR with classifier still pulls all the dependencies. I need to make a separate artifact ID. I'll fix this tonight.

**Comment by rickfast** [comment]
Only option is a shaded JAR for now. The old JAR already shaded the HTTP stuff, and so I just added Jackson as well. 

Would be a pain in the ass to get two artifacts working right now, and honestly, most people get annoyed with the Jackson dependencies.

```
    <dependency>
        <groupId>com.orbitz.consul</groupId>
        <artifactId>consul-client</artifactId>
        <version>0.12.0</version>
    </dependency>
```
