### ISSUE TITLE
Typo for cas on PutOptions

### ISSUE THREAD

**Issue by eduardolundgren** [OrbitzWorldwide/consul-client#132]
I am wondering if this is a typo:

https://github.com/OrbitzWorldwide/consul-client/blob/88e7abb4492410ca110289293e830303287964dd/src/main/java/com/orbitz/consul/option/PutOptions.java#L26

Accordingly docs, it should be passed as `cas` not `case`.

**Comment by rickfast** [comment]
Yes. It's a typo

**Comment by rickfast** [comment]
fixed f920eeb783ac4675a20fb3d6f83df7e74614acdb

**Comment by eduardolundgren** [comment]
Thanks!

**Comment by eduardolundgren** [comment]
Could you push a version with that fix?

**Comment by eduardolundgren** [comment]
Hi, just checking if you are going to release it or not, otherwise I will fork it. Thank you.

**Comment by rickfast** [comment]
I will release this evening when I get home

**Comment by rickfast** [comment]
alright 0.12.2 is released

**Comment by eduardolundgren** [comment]
Thanks.
