### ISSUE TITLE
Support Timeout for Checks

### ISSUE THREAD

**Issue by Bryann** [OrbitzWorldwide/consul-client#140]
Hi,

i don't know if this is the right place to ask. According to the consul API: https://www.consul.io/docs/agent/checks.html , you can specify a timeout of x seconds when register a check or a service (including a health check). I didn't see any chance to configure this property using the consul-client.

Is this feature missing? If yes, it's planned to implement this feature in one of the next releases?
I need to configure this property because the default timeout (which is 10 seconds) is not enough.

Best regards,

Bryan

**Comment by rickfast** [comment]
Yes it is missing. I will add it this morning

**Comment by rickfast** [comment]
Fixed by 6a6d67bca3a127c8e4ad0d941c1ebed708378b6a
