### ISSUE TITLE
Support Notes for Checks

### ISSUE THREAD

**Issue by Bryann** [OrbitzWorldwide/consul-client#141]
Hi again,

first of all, thanks for adding the timeout (Ticket https://github.com/OrbitzWorldwide/consul-client/issues/140) to the health-check. Im currently implementing the new version into our application.

Can you do the same for the "Notes" property?  So that we can add custom descriptions to the checks?
See https://www.consul.io/docs/agent/checks.html for details.

**Comment by Bryann** [comment]
I implemented the changes by myself, but i'm unable to push it. See attached files. 

[changes.zip](https://github.com/OrbitzWorldwide/consul-client/files/359259/changes.zip)

**Comment by rickfast** [comment]
Can you make a pull request?
