### ISSUE TITLE
ConsulCache empty if consul has no leader

### ISSUE THREAD

**Issue by dantheman46** [OrbitzWorldwide/consul-client#148]
Hello

problem with **ConsulCache**
when  ConsulResponse{response=null, lastContact=0, **knownLeader**=false, index=0}

there is a problem when consul cluster has no leader. e.g. working one of the three nodes.
It would be better solution to throw an exception than return clean the cache.

At the moment dev is not able to recognise if there is really no service instance or it is problem with consul cluster.

In case of cluster problem cache shouldn't be changed because service in 99% is working

Regards

**Comment by dantheman46** [comment]
@aantono 
@getfatday 
@flatiron32 
@dopuskh3 
@jasondaihl 

Could you check this out

thanks in advance
Regards

**Comment by rickfast** [comment]
fixed via fa70b81d8b9b035abe4790395f1759d42668e8da
