### ISSUE TITLE
HTTP checks

### ISSUE THREAD

**Issue by vkostetski** [OrbitzWorldwide/consul-client#15]
Will you provide HTTP-checks for services?

**Comment by rickfast** [comment]
Yes. We already do (unless I am misunderstanding the question).  See AgentClient

**Comment by vkostetski** [comment]
Consul checks has 3 types: script + interval, http + interval, ttl.
In AgentClient.Checks realization i see only following properties: script, interval and ttl, which cover only 2 types.

**Comment by rickfast** [comment]
ah.  I see it on the consul docs.  New feature.  I will implement this today.  Thanks!

**Comment by rickfast** [comment]
This work is done via commit <https://github.com/OrbitzWorldwide/consul-client/commit/c3ab7b069507aa72dca8617a5e7f27e45362cebe> . I will release it with 0.8.4
