### ISSUE TITLE
New release including #153

### ISSUE THREAD

**Issue by jeinwag** [OrbitzWorldwide/consul-client#154]
First, I'd like to thank you for your great work on this project!
May I ask you to please create a new release including #153? 
We sorely need this fix. 

Thansk!

**Comment by markus-wi** [comment]
:+1: 
I'm also eagerly waiting for this one to be released

**Comment by rickfast** [comment]
Releasing now. Sorry I've been away.

**Comment by rickfast** [comment]
`0.12.7` is released. sorry for the delay

**Comment by jeinwag** [comment]
Thanks, no problem!
