### ISSUE TITLE
Can we simulate consul Exec command using consul-client

### ISSUE THREAD

**Issue by nari-m** [OrbitzWorldwide/consul-client#155]
I would like to simulate consul exec command using consul-client java library. Is there a simple way to do it ?

**Comment by rickfast** [comment]
Upon reading the documentation on exec, I don't see an easy way to do this using the HTTP API only. It seems that it is based on events, so if you can reverse engineer the event that they're using for exec, you could potentially simulate it. I'm going to say it's out of scope for this library though.

**Comment by nari-m** [comment]
Thanks for your reply @rickfast. I did reverse engineered their consul exec command in java and using it now.
