### ISSUE TITLE
KVCache silently shortens key paths if multiple path elements have the same value

### ISSUE THREAD

**Issue by sgrimm-sg** [OrbitzWorldwide/consul-client#156]
If I have a key `foo/bar/bar/baz`, it is awkward to access using KVCache because KVCache constructs a `Set` of path elements (and thus the first `bar` path element is silently discarded). The use of sets means KVCache treats a key of `foo/bar/bar/baz` as identical to `foo/bar/baz/baz`.

**Comment by rickfast** [comment]
I'll take a look at this. Unfortunately, I'm unavailable for the next week, so it will be a little while. PRs welcome

**Comment by sgrimm-sg** [comment]
The PR is what I did locally and it works for my application, but of course I'm not sure if other users depend on side effects from the old version.

**Comment by rickfast** [comment]
I'm sure no one depends on that side effect. This implementation has been changed many times. Your implementation was similar to the original. I'll take a look back and make sure this doesn't have the same issues
