### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Crystark** [OrbitzWorldwide/consul-client#167]
Hi,

I'm now updating to the latest version (0.13.0) from consul-client 0.9.16 and I was wondering if there was a changelog somewhere I could read, besides the commits. I want to make sure there's no breaking change or compatibility issue with the consul version and have a recap of new features that could be useful.

Is that something you have ?
Thanks

**Comment by rickfast** [comment]
It's not, sorry. The major change between 0.9.x and 0.13.x is that the underlying HTTP client was changed from JAX-RS (impl provided by client code) to OKHTTP.  The API is exactly the same, save for new fields.

**Comment by Crystark** [comment]
Is there any new feature between those two version ?

Also would you consider adding a changelog for future releases ?
Thanks!

**Comment by rickfast** [comment]
Yes. There's lot of features. I try to add new fields to match changes in the Consul API (Prepared Queries, etc). I'll consider it, but unfortunately, I don't have as much time to work on this library lately.

**Comment by rickfast** [comment]
https://github.com/OrbitzWorldwide/consul-client/blob/master/CHANGELOG.md
