### ISSUE TITLE
behavior change : ConsulResponseCallback#onFailure now called in case entry does not exists

### ISSUE THREAD

**Issue by YannRobert** [OrbitzWorldwide/consul-client#173]
Today I tested an upgrade 
to latest ```0.13.1```
from version ```0.12.3```

and I found a change in behavior of the lib : 

When watching for change on an entry, 
Previously, the lib was calling ```com.orbitz.consul.async.ConsulResponseCallback#onComplete```
even when the server returns a HTTP status ```404```
Now, the lib is calling ```com.orbitz.consul.async.ConsulResponseCallback#onFailure```.

I am not sure that a ```404``` means a failure.
It seems to me it just means that the entry does not exists, which is not a failure, just a possible functional case. 

Previously, I was checking ```consulResponse.getResponse().isPresent()``` that was false in case of a ```404```. 

Imagine the case when a configuration entry is present for a while, then it is removed from Consul. The application needs to be notified that the entry was removed. Hence the call to ```com.orbitz.consul.async.ConsulResponseCallback#onComplete```.

```com.orbitz.consul.async.ConsulResponseCallback#onFailure``` is now called in case of a ```404```, the following parameter : ```com.orbitz.consul.ConsulException: Consul request failed with status [404]:  ```

The ```ConsulException``` does tell it is a ```404``` in the message, but this is a fragile way to tell the application about a functional case. The message could change in the future, then an application cannot rely on it to tell a ```404``` from any other error.

We should either make the lib : 
- call ```com.orbitz.consul.async.ConsulResponseCallback#onComplete``` like it was before
- or provide an actionable way to distinguish the functional case ```404 NOT FOUND``` from the ```Thowable``` passed to ```com.orbitz.consul.async.ConsulResponseCallback#onFailure```

I think I prefer the first solution.

**Comment by YannRobert** [comment]
see https://www.consul.io/intro/getting-started/kv.html

The ```404``` response contains a ```X-Consul-Index``` header that is important to continue to monitor further changes.

In case of a KV watch, a ```404``` is a valid response HTTP status that provides information.

Method ```com.orbitz.consul.util.Http#extractConsulResponse(retrofit2.Call<T>, com.orbitz.consul.async.ConsulResponseCallback<T>)``` should consider the response is successfull when the code is ```404``` ; at least when it is called by the ```KeyValueClient```

**Comment by YannRobert** [comment]
since #161

**Comment by rickfast** [comment]
I'll see if I can get a fix in for this today

**Comment by rickfast** [comment]
fixed by d8a51b446dc99613da98eb7e5156cbe8eb380c26

**Comment by YannRobert** [comment]
it's working, thanks
