### ISSUE TITLE
Add a "why" to the section about blocking call

### ISSUE THREAD

**Issue by RichoDemus** [OrbitzWorldwide/consul-client#174]
in the section "Example 4: Blocking call for value" there is a lot of code to get a value.

But since there is a section about how to do blocking calls it seems like the default is non-blocking and that this is the way to do blocking calls, but then there is just a getValue() method in the keyvalue client, doesn't that allow a much simpler way of doing a blocking call to get a value?

Either I'm missing something about what section 4 describes or there's simply a much easier way to do it know and the documentation doesn't reflect this :)

**Comment by robbert229** [comment]
I created a pr with a single line of documentation to help describe what the blocking call is.

**Comment by RichoDemus** [comment]
Ah! So it's kind of like a one-shot subscribe to changes for a value?

**Comment by robbert229** [comment]
Exactly, though it doesn't guarantee that the change actually occurs. 
* It may time out
* A write may be idempotent ( the value is set to foo, and some other process sets it to foo )
