### ISSUE TITLE
Support for transactions.

### ISSUE THREAD

**Issue by pviotti** [OrbitzWorldwide/consul-client#177]
It would be nice if this library supported transactions, as implemented in Consul >=0.6 key-value API.  
https://www.consul.io/docs/agent/http/kv.html#txn

**Comment by rickfast** [comment]
I have this on a local branch. Hopefully I'll get it in within the next couple days

**Comment by rickfast** [comment]
fixed 731d28201a272734b9ddb169ce3e462c8c9da936
