### ISSUE TITLE
maintenance mode

### ISSUE THREAD

**Issue by philippeu** [OrbitzWorldwide/consul-client#183]
Hi,
Is there a plan to add the maintenance mode in the agent api?
[https://www.consul.io/docs/agent/http/agent.html#agent_service_maintenance](url)
thanks

**Comment by rickfast** [comment]
I'm sure it can be easily added. I'm overseas for the next week, but I'll add it when I get back. If you need it now, it should be an easy PR.

**Comment by philippeu** [comment]
there is no rush, thanks for the quick answer!

**Comment by rickfast** [comment]
fixed via f459947cbbb645699deed63152c6c82a3ab07f12
