### ISSUE TITLE
Can provide example of how to subscribe to KV changes?

### ISSUE THREAD

**Issue by maorcatmyheritage** [OrbitzWorldwide/consul-client#186]
Hi,

Can you please provide me example of subscribing to changes to the key-value store?

I tried this: 
`KVCache kvCache = KVCache.newCache(consul.keyValueClient(), path, watchSeconds);
kvCache.addListener(new ConsulCache.Listener<String, Value>() {
        public void notify(Map<String, Value> map) {
            // Key changed
        }
});`

But that didn't work and notify() isn't called when I change value in the Consul cluster.

Thanks,
Maor

**Comment by rickfast** [comment]
Call `start()` on the cache and it will work

**Comment by maorcatmyheritage** [comment]
My bad. I called `start()`, just forgot to add it to my message...
Right after calling `start()`, the `notify()` is being called but no call is made when changing values in the server (through the Consul UI). Can you explain how the watch is done? Is it using the blocking HTTP API? Can you point the code that does this?

One more question, how should the monitor flow should look like?
I guess that when the watchSeconds timeout reaches changes are not captured anymore. What should be done then?

**Comment by rickfast** [comment]
Yes, the `KVCache` uses the blocking HTTP API calls - the code that makes this call is here: https://github.com/OrbitzWorldwide/consul-client/blob/master/src/main/java/com/orbitz/consul/KeyValueClient.java#L96

when `watchSeconds` elapses, the cache will re-initiate a connection.

**Comment by maorcatmyheritage** [comment]
Got it. It is now working well! Thank you very much for your help.

**Comment by dilipmevada** [comment]
Hi,
How to get latest changes of Key Value in .Net, Do we I required special code for it?

Please give me some sample code for it.
