### ISSUE TITLE
Add CatalogOptions to KeyValueClient, or add Datacenter to QueryOptions

### ISSUE THREAD

**Issue by dtertman** [OrbitzWorldwide/consul-client#187]
Sometimes it is necessary to query a Key/Value from another data center.  The most visible use-case is a developer working locally on the laptop/desktop, but wanting to act like a QA or PROD server.  Rather than running a local Consul instance, changing its datacenter, and redoing all of its joins, it would be much better to just tap into a consistent web API endpoint and use the existing WAN gossip.

The `KeyValueClient` currently doesn't support this, even though the underlying Consul API does.  `QueryOptions` does not have a `datacenter` parameter, and `CatalogOptions`, which has a `datacenter`, isn't accepted by any of the `KeyValueClient` methods.

`HealthClient`, on the other hand, does support this method, through `CatalogOptions`.

**Comment by rickfast** [comment]
Hmmm surprised I never added that. Also surprised it hasn't come up as an issue. Fixed by ef3ca727858ea7a627ca06576a7834b4df13a723
