### ISSUE TITLE
How to register my service with path?

### ISSUE THREAD

**Issue by Arun-Trichy** [OrbitzWorldwide/consul-client#189]
I have my set of services running at 

> http://localhost:80/service1
> http://localhost:80/service2
> http://localhost:80/service1/a
> http://localhost:80/service2/b

How do I register these services into consul client?

As, the register service does not have any options for giving a path other than the port.
> https://www.consul.io/docs/agent/http/agent.html#agent_service_register

**Comment by Arun-Trichy** [comment]
I figured out the issue.

Thank You.

**Comment by YuanPan** [comment]
@Arun-Trichy how did you solved the problem?
