### ISSUE TITLE
Telemetry Deserialization Issue

### ISSUE THREAD

**Issue by nirajpatel** [OrbitzWorldwide/consul-client#190]
Hi! It seems like in version 0.7.0 of consul the following String should be an array.

https://github.com/OrbitzWorldwide/consul-client/blob/a4cfd6aa94ad430c17872069205b427f26a75bbc/src/main/java/com/orbitz/consul/model/agent/Telemetry.java#L33

 I have tested making that change locally and everything seems to work properly.

**Comment by rickfast** [comment]
If you already made the change locally can you make a PR then?

**Comment by rickfast** [comment]
fixed 68039e88ac1b6e26bdcb6b51464e776bf24724da

**Comment by nirajpatel** [comment]
Thanks @rickfast! Next time I will send a PR. Sorry about that. When will the next release be cut?

**Comment by rickfast** [comment]
`0.13.6` is now available in central and bintray

**Comment by nirajpatel** [comment]
Thank you sir :)
