### ISSUE TITLE
Support for adding custom headers

### ISSUE THREAD

**Issue by DanielCharczynski** [OrbitzWorldwide/consul-client#192]
Is there possibility to add custom http headers?
We would like to use this lib, but we have proxy that requires some additional headers.
Our platform doesn't support consul agents and we will use it remontly.

**Comment by rickfast** [comment]
Do you need them to be dynamic, or can they be defined at Consul client creation time?

**Comment by rickfast** [comment]
use `Consul.Builder.withHeaders(Map<String, String> headers` introduced in 086b4b4b29fc45193ccc6c73f156fc430645c81b
