### ISSUE TITLE
Key/Value Cache - issue with getKeyExtractorFunction()

### ISSUE THREAD

**Issue by yfouquet-criteo** [OrbitzWorldwide/consul-client#196]
Hi everyone,
It looks to me this method was working well (according to my needs) until October 4th when commit [159](https://github.com/OrbitzWorldwide/consul-client/commit/37149767ba21a6d26d126ff675a6e9332ebbd033) changed the way the method was implemented, and its behavior.
Then, 2 fixes were merged: [fix1](https://github.com/OrbitzWorldwide/consul-client/commit/0787000829195824154817ae47eaf52fdd2dd928) and [fix2](https://github.com/OrbitzWorldwide/consul-client/commit/94031ec02dd464fd23de8d03b7989606898b99e8).
Today, i still face issues with this method. If i am looking for "a/b" and two keys exist "a/b" and "a/bc", the method will throw an exception. This problem did not exist before October 4th.

I am willing to fix it but can we make clear the expectation of this method before doing so. 
Following is how i feel the method should work:
 - looking for "a/b" got "a/b" return ""
 - looking for "/a/b" got "a/b" return ""
 - looking for "a/b/" got "a/b" return ""
 - looking for "a/b" got "a/b/" return ""
 - looking for "a/b/" got "a/b/c" return "c"
 - looking for "a/b" got "a/bc" return "bc"
 - looking for "/" got "a/b" return "a/b"
 - looking for "" got "a/b" return "a/b"

@rickfast @IgnasD @sgrimm-sg Can we agree on that?

**Comment by yfouquet-criteo** [comment]
Note that if we cannot agree, it is still possible to change KVCache so that it is possible to override the method as done by @killerwhile in this [commit](https://github.com/OrbitzWorldwide/consul-client/commit/30870acc23ee7bce68feb681ca369faca215900d)

**Comment by rickfast** [comment]
This seems to satisfy the most cases out of every PR I've merged regarding the KVCache, so I'm okay with it.
