### ISSUE TITLE
Accessing consul instance on host machine from docker container

### ISSUE THREAD

**Issue by vicmosin** [OrbitzWorldwide/consul-client#200]
Tried different options (providing local, 127.0.0.1 and real IP addresses) to container, but still doesn't work.. App inside container can't find hosts.

`docker run -e consul.host=http://consul.service.consul:8500 -p 6080:8080 container`

```
return Consul.builder()
            .withUrl(host)
            .build();
```
```

Caused by: java.net.UnknownHostException: consul.service.consul: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_72-internal]
```

**Comment by rickfast** [comment]
Can you try a dig on the DNS name from inside the container? I don't think this is a problem with the client

**Comment by rickfast** [comment]
assuming problem is fixed since you didn't reply. closing for now
