### ISSUE TITLE
Allow to override default read timeout for a specific API

### ISSUE THREAD

**Issue by lbertrand** [OrbitzWorldwide/consul-client#202]
In order to use the library for normal API and also the blocking API, in order to watch KV modifications, for example, we have to create 2 consul client as the read timeout is set up at the client level ,but can't be overriden on a specific API call.

If we want to reuse the same client, either we have to accept a longer timeout for normal APIs, like if we want to block for watching for 5 minutes. Or accept that the blocking API will only block for 10 seconds, for example, which is the default for normal operation?

**Comment by rickfast** [comment]
I'll take a look at options for this. Not sure if there's a clean way to do this and preserve the current API

**Comment by yfouquet** [comment]
Hi @lbertrand ,
I think that https://github.com/OrbitzWorldwide/consul-client/pull/289 fixed your issue, and it can be closed.
