### ISSUE TITLE
Builder patterns are reversed

### ISSUE THREAD

**Issue by shveik** [OrbitzWorldwide/consul-client#203]
Hi, first of all, great library, very useful. I was trying to use the ImmutablePutOptions and ran into a "reversed build pattern". Is there any reason why it's 

`ImmutablePutOptions.builder().build().withCas(...)` instead of 

ImmutablePutOptions.builder.withCas(...).**build()**

Seems like standard pattern is to get an instance of the builder, set the options, and then finalize it with build(). 

thanks!

**Comment by rickfast** [comment]
The builders are generated using the "immutables" library, so I don't really have control over how theey work. Calling any "with*" method makes a full immutable copy of the object, so it's a convenience method to avoid the whole build chain.

**Comment by gjesse** [comment]
@shveik, you don't have to call the `build()` first, you can create a single object like

`ImmutablePutOptions.builder().cas(...).build()`, which is what i think you're looking for.

Once you have the object, using the `with` syntax is nice if you need a modified copy.

**Comment by shveik** [comment]
yes, thank you for pointing it out, i saw these after i submitted the issue. it was more of a question anyways.
