### ISSUE TITLE
TLSSkipVerify support from consul 0.7.2

### ISSUE THREAD

**Issue by DanielCharczynski** [OrbitzWorldwide/consul-client#206]
Could you add TLSSkipVerify flag support?

https://www.consul.io/docs/agent/http/agent.html#agent_service_register

Thanks

**Comment by rickfast** [comment]
I'll see if I can get to it this week. Should be an easy PR if you need it sooner.

**Comment by rickfast** [comment]
fixed - 962d6b86dbc023220e124d89f849116855ccabb1

**Comment by DanielCharczynski** [comment]
There is no possibility to set up this value and register in consul
