### ISSUE TITLE
set up TLSSkipVerify during registrations

### ISSUE THREAD

**Issue by DanielCharczynski** [OrbitzWorldwide/consul-client#208]

**Comment by rickfast** [comment]
Can you use 'AgentClient.register(Registration)'?

**Comment by DanielCharczynski** [comment]
Yes but ImmutableRegCheck.Builder does not provide possibility to set TLSSkipVerify flag

**Comment by rickfast** [comment]
Yes it does - see my commit -> 962d6b86dbc023220e124d89f849116855ccabb1

Just tried it:

```java
public static RegCheck check = ImmutableRegCheck.builder().tlsSkipVerify(true).build();
```

If you're testing the source, make sure you regenerate the generated immutables. I'll release a new version later today

**Comment by DanielCharczynski** [comment]
OK I didn't notice that immutables are generated.
I'll be very grateful for the release.

Thanks a lot

**Comment by rickfast** [comment]
0.13.9 is released
