### ISSUE TITLE
KV client- putValue() method does not support pasing token

### ISSUE THREAD

**Issue by dpish7** [OrbitzWorldwide/consul-client#210]
Hello,

I noticed that the KeyValueClient does not support passing a token(acl token) for a PUT to the KV store.The client does have GET methods that let you pass a token as a query option.

The client has putValue() methods with PutOptions but PutOptions currently only supports 'cas', 'acquire' and 'release'.
There is not support for  consul PUT v1/kv/<key>?token=<token>.

Can PutOptions be updated to allow passing a token parameter as well?

**Comment by rickfast** [comment]
fixed here 4fbe6b2c90fb333ceaabfb2267eeeae5bf987814
