### ISSUE TITLE
SERIOUS PROBLEM ! - this lib wont work since consul 0.7.3 

### ISSUE THREAD

**Issue by DanielCharczynski** [OrbitzWorldwide/consul-client#211]
Change log
https://github.com/hashicorp/consul/blob/master/CHANGELOG.md

> Improved Blocking Queries: Consul's blocking query implementation was improved to provide a much more fine-grained mechanism for detecting changes. For example, in previous versions of Consul blocking to wait on a change to a specific service would result in a wake up if any service changed. Now, wake ups are scoped to the specific service being watched, if possible. This support has been added to all endpoints that support blocking queries, nothing new is required to take advantage of this feature. [GH-2671]

but 
package okhttp3;

public final class Dispatcher {
  private int maxRequests = 64;
  private int maxRequestsPerHost = 5;

The easiest way is to allow to set this values to MAX_INT

**Comment by DanielCharczynski** [comment]
it is important to us 
 look at this
https://github.com/OrbitzWorldwide/consul-client/pull/212

I you accept the PR please release new version

**Comment by rickfast** [comment]
merged and release in 0.13.10
