### ISSUE TITLE
Support healthcheck initial state during service registration

### ISSUE THREAD

**Issue by odiszapc** [OrbitzWorldwide/consul-client#213]
Here https://www.consul.io/docs/agent/http/agent.html#agent_service_register
in **/v1/agent/service/register**

> The Status field can be provided to specify the initial state of the health check.

Do we support this field in java api? Looks like not, fix me if I'm wrong. If there has no support are you ok with me to provide a pull request?

**Comment by rickfast** [comment]
i am ok with a PR for this.

**Comment by rickfast** [comment]
fixed in 4fbe6b2c90fb333ceaabfb2267eeeae5bf987814 - 0.13.10
