### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by wenhx8** [OrbitzWorldwide/consul-client#215]
when i shutdown tomcat that use consul-client  in servlet on destroy function, tomcat log appear below warning:
07-Feb-2017 21:40:02.367 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [autodeploy] appears to have started a thread named [OkHttp ConnectionPool] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.Object.wait(Object.java:460)
 okhttp3.ConnectionPool$1.run(ConnectionPool.java:66)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)

it seem a bug,please fix

**Comment by rickfast** [comment]
This isn't a memory leak. It's just warning about threads that didn't stop when tomcat shutdown. I just merged a change that will change the threads to daemon threads. Will likely make this WARNING go away.
