### ISSUE TITLE
Add static method in State to get it by name

### ISSUE THREAD

**Issue by Suvitruf** [OrbitzWorldwide/consul-client#24]
Hi. 
When I use this lib, I need to compare result of `HealthClient.getHealthyServiceInstances` and `HealthClient.getAllServiceInstances` with `State`.

But in `HealthCheck` class status represents as string. So, mb it's not bad idea to make method for getting State by it's name like c6b022f8d1cd2250d359f9600d88b6037712552e ?

**Comment by rickfast** [comment]
sounds good.  make a pull request with the change and I'll merge it.  thanks!

**Comment by Suvitruf** [comment]
Ok. Did it #25 
But this pull request has to many useless commits also =/

**Comment by rickfast** [comment]
See https://github.com/OrbitzWorldwide/consul-client/commit/0dea4d08f6b54dfd64224e6a4b0e8bf4d7bf7740
