### ISSUE TITLE
Prepared query with template

### ISSUE THREAD

**Issue by elleFlorio** [OrbitzWorldwide/consul-client#242]
Hi,

I was trying to create a prepared query using a template, but I couldn't figure out how to do it. Looking into the code, seems that the PreparedQuery class doesn't have a field to store the template. Is it a "bug" or am I missing something?

Thanks.

**Comment by elleFlorio** [comment]
Anyway, if it is a bug I fixed it. If you want I can do a pull request. ;-)

**Comment by rickfast** [comment]
Looks like a bug - forgot to add the field to PQ :/ PR is welcome. I can release a new version after

**Comment by rickfast** [comment]
Yup

**Comment by elleFlorio** [comment]
Ok, done. Thanks!
