### ISSUE TITLE
KeyValueClient: getValue(s) functions' return value isn't wrapped with ConsulResponse 

### ISSUE THREAD

**Issue by shays10** [OrbitzWorldwide/consul-client#243]
Blocking calls to `getValues(String key, QueryOptions queryOptions)` aren't returning `ConsulResponse<List<Value>>` but returning `List<Value>`
(In my case, I need the index value from the response)

**Comment by rickfast** [comment]
We just ran into this at Orbitz/Expedia for a project. We will add this shortly.

**Comment by shays10** [comment]
Great, thanks!
