### ISSUE TITLE
Make the ConsulCache wait time less than OkHttp read timeout

### ISSUE THREAD

**Issue by alugowski** [OrbitzWorldwide/consul-client#255]
I think the defaults could be adjusted to have fewer people experience the constant timeout as seen by #135 .

There are two timers in a cache. One is the read timeout, which is how long OkHttp will wait for a response (OkHttp default is 10s). The second is the blocking request wait time, and `consul-client` default is _also_ 10s.

But see this in the Consul blocking queries docs (https://www.consul.io/api/index.html#blocking-queries): 

> A small random amount of additional wait time is added to the supplied maximum wait time to spread out the wake up time of any concurrent requests. This adds up to wait / 16 additional time to the maximum duration.

What's happening is that that jitter makes Consul reply in slightly longer than 10s, which makes OkHttp time out with the ugly exception seen in #135.

I suggest making the default `watchSeconds` value 8s, so that this extra jitter (plus a little margin) makes it much less likely for default OkHttp configs to cause time outs.

**Comment by yfouquet** [comment]
Hi @alugowski ,
I think that https://github.com/OrbitzWorldwide/consul-client/pull/289 fixed your issue, and it can be closed.
Instead of setting the default watch to 8 seconds, it increased the timeout depending on the wait duration.

**Comment by alugowski** [comment]
That looks like it should work, thanks!
