### ISSUE TITLE
Add compatibility table

### ISSUE THREAD

**Issue by Hronom** [OrbitzWorldwide/consul-client#260]
Please add compatibility table, I need to know with what version of Consul this client is compatible.
Or at least what version of Consul you use while develop this plugin.

Thanks in advance!

**Comment by rickfast** [comment]
I've made an effort to maintain backwards compatibility w/ the client. When a new version of Consul comes out, we add new API fields as needed. At Expedia, we are using the latest client version with Consul 0.7.1. I'm not going to go back and test each version of Consul w/ the client. Is there a specific problem you're having?

**Comment by Hronom** [comment]
No problems, I'm just switching to `0.16.3` of client and I want to make sure that it works well with Consul `0.9.2`

**Comment by rickfast** [comment]
My guess is that the worst case is that a few fields need to be added. I haven't tried 0.9.x yet. Closing this issue. If you have an issue with 0.9 feel free to file a new issue or PR
