### ISSUE TITLE
TaggedAddresses should support 'lan'

### ISSUE THREAD

**Issue by kgignatyev-inspur** [OrbitzWorldwide/consul-client#261]
com.orbitz.consul.model.catalog.TaggedAddresses should support 'lan' attribute as a minimum, better yet make it to support any number of addresses  per 
https://www.consul.io/api/catalog.html#taggedaddresses
 here is example registration request 

{
  "Datacenter": "dc1",
  "ID": "40e4a748-2192-161a-0510-9bf59fe950b5",
  "Node": "foobar",
  "Address": "192.168.10.10",
  "TaggedAddresses": {
    "lan": "192.168.10.10",
    "wan": "10.0.10.10"
  },
  "NodeMeta": {
    "somekey": "somevalue"
  },
  "Service": {
    "ID": "redis1",
    "Service": "redis",
    "Tags": [
      "primary",
      "v1"
    ],
    "Address": "127.0.0.1",
    "Port": 8000
  },
  "Check": {
    "Node": "foobar",
    "CheckID": "service:redis1",
    "Name": "Redis health check",
    "Notes": "Script based health check",
    "Status": "passing",
    "ServiceID": "redis1"
  }
}
»

**Comment by rickfast** [comment]
fixed 2220fe4969b4d1f91fe380543b717ca11be74d72
