### ISSUE TITLE
retrofit update

### ISSUE THREAD

**Issue by DanielCharczynski** [OrbitzWorldwide/consul-client#264]
Coud you update retrofit dependency to the newest one and release new version?

<dependency>
  <groupId>com.squareup.retrofit2</groupId>
  <artifactId>retrofit</artifactId>
  <version>2.3.0</version>
</dependency>

There are some fixed issues in okhttp 3.9.0

Thanks

**Comment by rickfast** [comment]
aa838f7a3c6ee6c1640dc8f4cf998176bfab46cc

**Comment by rickfast** [comment]
`0.16.4` is uploading now
