### ISSUE TITLE
Add client support for Watches

### ISSUE THREAD

**Issue by hotmeatballsoup** [OrbitzWorldwide/consul-client#31]
It would be great if real-time notification of config changes (KV data changes) were possible on the client-side.

I *believe* this concept is supported in the "raw" Consult API via [watches](https://consul.io/docs/agent/watches.html), however I don't see that concept supported by this library.

The idea is simple:
* Allow clients to register their own callbacks/watches with the Consul cluster
* The callback/watch will now execute when the cluster senses a change to config data (or anything really)

The idea is to allow GOSSIP to "do its thing" and update clients in real-time, rather than forcing clients to poll.

**Comment by rickfast** [comment]
We do support this already.  We actually use this concept in production.  Notice the methods in the kv client and health client that accept callbacks.  Although not all of the "watchable" endpoints have been implemented.  The plumbing is there.

**Comment by hotmeatballsoup** [comment]
Very nice! Are these `ConsulResponseCallback` based on polling or are they *actually* real callbacks, as "pushed" from the Consul server?

**Comment by rickfast** [comment]
> Watches are implemented using blocking queries in the HTTP API. Agents automatically make the proper API calls to watch for changes and inform a handler when the data view has updated.

The only other way I see to implement watches is with the "handler" approach, which involves giving Consul a script to execute when watched attributes change.  This seems out of scope for this client.

**Comment by rickfast** [comment]
They're based on long polling.  I don't see another way to implement it using the HTTP API.

**Comment by hotmeatballsoup** [comment]
Sure, ok thanks for the help here I'll close the ticket!
