### ISSUE TITLE
Publish artifacts to maven central

### ISSUE THREAD

**Issue by norbertpotocki** [OrbitzWorldwide/consul-client#32]
Hi,

could you please publish consul-client to maven central repository?

**Comment by rickfast** [comment]
I can try to do this next week, but I'm out of town at the moment.  Is there a reason you can't use JCenter?

**Comment by hotmeatballsoup** [comment]
I can't speak for norbert but my guess is that I'm not the only one who can't resolve the jar.

I think your JCenter coordinates may be hosed. The [JCenter link](http://dl.bintray.com/orbitz/consul-client/com/orbitz/consul/consul-client/0.9.5/#consul-client-0.9.5.jar) on your `README.md` gives a "`The requested path was not found.`"-error and the jar is not resolving when I run Gradle locally.

To reproduce, `build.gradle`:

    repositories {
        mavenLocal()
        mavenCentral()
        jcenter()
    }

    dependencies {
        compile 'com.orbitz.consul:consul-client:0.9.5'
    }

Then run `gradle eclipse` and nothing resolves.

Are you positive those coordinates are correct?!

**Comment by rickfast** [comment]
Interesting.  We cache JCenter in Artifactory and haven't had a problem.  I'll work to resolve this

**Comment by rickfast** [comment]
JCenter path got borked on this release.  When I'm back at my laptop I will resolve

**Comment by hotmeatballsoup** [comment]
Thank you! BTW not complaining here, this is a great lib you're providing here, much appreciated!

**Comment by rickfast** [comment]
No worries.  It was my bad.  The artifacts have been re-published (correctly).  Let me know if there's any other issues.

@norbertpotocki - I will be back at work Thursday, and I will see what I can do about publishing to Central.

**Comment by norbertpotocki** [comment]
Thanks @rickfast. I'm using your library as a dependency for my [configuration library](https://github.com/cfg4j/cfg4j) which is hosted only on Maven Central for now. So all my users need to add both repositories for the dependency to be found. I'm going to publish to JCenter to fix that soon.

I also noticed that some maven users prefer (or have) to stick to the default repo and can't use JCenter artifacts. It would be nice to support them too.

**Comment by rickfast** [comment]
No problem.  I did the initial work with Sonatype to get accepted, I just have to set up a user token or something to sync between JCenter and Central.  Once I'm back in the office I'll tackle it.  Thanks for the patience!

**Comment by rickfast** [comment]
@norbertpotocki I have released ```0.9.6-RC1``` to Central.  Give it a whirl and if everything's good, I'll close this ticket.  Enjoy.

```xml
<dependency>
  <groupId>com.orbitz.consul</groupId>
  <artifactId>consul-client</artifactId>
  <version>0.9.6-RC1</version>
</dependency>
```

**Comment by norbertpotocki** [comment]
Thanks, works great. Out of curiosity - why RC1 on maven central and GA on jcenter?

**Comment by rickfast** [comment]
RC1 was just a test.  I will sync GA today.  Thanks!

**Comment by rickfast** [comment]
```0.9.6``` is now available
