### ISSUE TITLE
Agent join is not supported

### ISSUE THREAD

**Issue by kongchen** [OrbitzWorldwide/consul-client#33]
https://www.consul.io/docs/agent/http/agent.html#agent_join

I didn't find join method in `AgentClient`, could anyone help?

**Comment by rickfast** [comment]
I will add it today.  Thanks!

**Comment by rickfast** [comment]
Fixed by https://github.com/OrbitzWorldwide/consul-client/commit/5173099db307554e66eec05f6b9d22fab07fe445

I will cut a release in a little bit.

**Comment by rickfast** [comment]
FYI ```0.9.5``` is now available with this change.

**Comment by kongchen** [comment]
Thanks!
