### ISSUE TITLE
Documention appears incorrect for Pass/Check

### ISSUE THREAD

**Issue by bearrito** [OrbitzWorldwide/consul-client#36]
In the README we see `agent.pass()` while the agent pass signature requires a `agent.pass(checkId)`

It isn't clear that this checkId is the same as the serviceId. Using the serviceId as the checkId doesn't work for me.

**Comment by rickfast** [comment]
Looks like I've done a poor job keeping the README in sync with the code.  The agent check methods have changed significantly.  I will update the docs soon.

**Comment by rickfast** [comment]
Calling ```pass()``` with your service ID should prepend ```service:``` to create the Check ID that was created when you registered your service.

So if your service ID is ```my-service```, you should be able to just call ```pass``` with that as the parameter.

**Comment by rickfast** [comment]
33b8e5dd54f0f2ede2aa885ce1945e9220c3ec19 and e3e630a7007410de03aa71204242b66b26f1a74d should clear this up.  Let me know if it does and I will close this issue.

A pull request a few months again added in the ```service:``` prefix to any check using the ```pass/warn/fail``` convenience methods.  I added another set ```passCheck/warnCheck/failCheck``` that can be used for non-service level checks.  Another option is just to call ```check``` with the Check ID.

**Comment by bearrito** [comment]
LGTM.
