### ISSUE TITLE
Immutables & java8

### ISSUE THREAD

**Issue by gjesse** [OrbitzWorldwide/consul-client#42]
I have been looking over the code, and I think it could benefit from something like the following : https://github.com/gjesse/consul-client/commit/e11c04a67e9329f2fd3d74eb8fc0a741869921df

If this is something you'd be interested in, I can take a crack at updating the remaining model classes for it.

Also, is there any chance of updating this library to java8?

**Comment by rickfast** [comment]
Originally I made this lib w/ Java 8, but there are a number of consumers on older versions of Java.

I'll take a peek at the immutable stuff this weekend and get back at you.

Thanks!

**Comment by rickfast** [comment]
I like the immutable idea.  I wonder if we can do it but leave "get" on the accessors.  This is mostly so upgrades to 0.9.8+ aren't painful.
