### ISSUE TITLE
Error establiching connection with consul server

### ISSUE THREAD

**Issue by GLE81** [OrbitzWorldwide/consul-client#56]
Hi,

I'm trying to integrate consul-client in my webapplication. I'm executing a test where everytime that the library try to connect to the consul server retrieve the following error "java.lang.NoSuchMethodError: javax.ws.rs.core.Response.close()V" in the line 79 of agentClient. I tried to debug or fix this error but every source code I download doesn't compile, it has errors of no class found like ImmutableCheck and ImmutableRegistration that aren't in the project.

I don't know if I forget something or if I have something wrong.

	<dependency>
	  <groupId>com.orbitz.consul</groupId>
	  <artifactId>consul-client</artifactId>
	  <version>0.9.8</version>
	</dependency>
        <dependency>
	   <groupId>org.apache.cxf</groupId>
	   <artifactId>cxf-rt-rs-client</artifactId>
	   <version>3.0.4</version>
        </dependency>

I'm using Spring 4.0.7.RELEASE.

**Comment by rickfast** [comment]
Hi
Looks like a JAX-RS version conflict on your classpath.  As far as ```ImmutableCheck``` goes, this is a new change in 0.9.8 that I think might still need some work.  The class in question is supposed to be generated dynamically, but a number of people have had issues with it.  Suggest you try 0.9.7 instead, which is quite stable.  I'm working to fix issues with 0.9.8.

**Comment by gjesse** [comment]
For the Immutable* classes you need to setup your IDE to process the annotations - see http://immutables.github.io/apt.html for more info. (Note I also had to manually mark the 'generated-sources' folder as a "generated source root" in intellij)

@rickfast unless you are thinking of removing these i can add some instructions to the README about it

**Comment by gjesse** [comment]
Also, I @GLE81, I tried replicating your error with a minimal setup and it worked fine, so I think Rick is correct about the source of your original issue.

**Comment by rickfast** [comment]
I haven't played with 0.9.8 yet, but a coworker had issues.  We should add a Development section on the README.

**Comment by rickfast** [comment]
@GLE81 you should have ```javax.ws.rs:javax.ws.rs-api:2.0.1``` on your classpath, and no other JAX-RS API versions.

If you're using Gradle, you can inspect version clashes with 
```sh
./gradlew dependencyInsight --dependency=javax.ws.rs-api
```
which will show if there's two versions on the classpath.

**Comment by gjesse** [comment]
> We should add a Development section on the README.

I can write something up today for it

**Comment by GLE81** [comment]
Hi,

I tried with version 0.9.7 and dependency javax.ws.rs:javax.ws.rs-api:2.0.1 and it still doesn't work. I'm continuing looking if I can find the problem anyway here is my pom.xml.

<properties>
		<spring.version>4.0.9.RELEASE</spring.version>
		<log4j.version>1.2.17</log4j.version>
		<jdk.version>1.7</jdk.version>
		<context.path>SpringRestSecurityOauth</context.path>
		<spring.security.version>3.2.5.RELEASE</spring.security.version>
	</properties>
 	<dependencies>
	        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>        
	       <dependency>
        <groupId>org.mortbay.jetty</groupId>
        <artifactId>jsp-2.1</artifactId>
        <version>6.0.0</version>
      </dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-io</artifactId>
			<version>1.3.2</version>
		</dependency>
		
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>${log4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
			<version>${spring.version}</version>
		</dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <version>${spring.version}</version>
            <scope>test</scope>
        </dependency>
		
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-web</artifactId>
			<version>${spring.security.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-config</artifactId>
			<version>${spring.security.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security.oauth</groupId>
			<artifactId>spring-security-oauth2</artifactId>
			<version>2.0.7.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.2.2</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.jackson</groupId>
			<artifactId>jackson-mapper-asl</artifactId>
			<version>1.9.10</version>
		</dependency>
		<dependency>
			<groupId>commons-httpclient</groupId>
			<artifactId>commons-httpclient</artifactId>
			<version>3.1</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-support</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.0.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.indra.security.oauth2</groupId>
			<artifactId>springSecurityOauth2Client</artifactId>
			<version>0.1</version>
		</dependency>
		    <dependency>
		        <groupId>com.orbitz.consul</groupId>
		        <artifactId>consul-client</artifactId>
		        <version>0.9.7</version>
		    </dependency>
<dependency>
	<groupId>org.apache.cxf</groupId>
	<artifactId>cxf-rt-rs-client</artifactId>
	<version>3.0.3</version>
</dependency>
<dependency>
	<groupId>org.apache.cxf</groupId>
	<artifactId>cxf-rt-transports-http-hc</artifactId>
	<version>3.0.3</version>
</dependency>
		   <dependency>
	<groupId>javax.ws.rs</groupId>
	<artifactId>javax.ws.rs-api</artifactId>
	<version>2.0.1</version>
</dependency>
	</dependencies>
  	<build>
		<finalName>${pom.artifactId}</finalName>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${jdk.version}</source>
					<target>${jdk.version}</target>
				</configuration>
			</plugin>
			      



















		</plugins>
	</build>

**Comment by GLE81** [comment]
OK. I just imported the 0.9.7 source code in my workspace and now is working, I'm going to continue testing to find what happened when I use the library.

**Comment by gjesse** [comment]
@GLE81, I'm not sure that's a good solution - likely it's altering the classpath in your dev environment, but it could be that the issue still occurs when you build for alternate environments.

I recommend that you run mvn dependency:tree from the command line - that will list all your dependencies, and their dependencies in turn to see which one is pulling in the conflicting javax.ws.rs-api   version. 

You could also then try experimenting with excluding the conflicting dependency.

**Comment by rickfast** [comment]
@GLE81 is this still an issue? If not, I'm going to close this issue. Thanks
