### ISSUE TITLE
Add ability to register multiple checks per service

### ISSUE THREAD

**Issue by vkostetski** [OrbitzWorldwide/consul-client#59]
This feature has not benn published in docs yet, but this request works fine:
Req: http://.../v1/agent/service/register
Body: 
{
  "ID": "crab_net",
  "Name": "crab_net",
  "Tags": [
    "master",
    "v1",
    "crab"
  ],
  "Address": "...",
  "Port": 22037,
  "Checks": [{
    "HTTP": "http://127.0.0.1:22037",
    "Interval": "10s"
  },
  {
    "HTTP": "http://127.0.0.1:22038",
    "Interval": "30s"
  }]
}

More info: https://github.com/hashicorp/consul/issues/230

**Comment by rickfast** [comment]
We can support this. I will try and find time this week to investigate. Pull requests welcome!

**Comment by gjesse** [comment]
i'd be happy to take a crack at it, will have a bit of time this afternoon to check it out

**Comment by rickfast** [comment]
this feature is released in ```com.orbitz.consul:consul-client:0.9.10```
