### ISSUE TITLE
ImmutablePutOptions is missing

### ISSUE THREAD

**Issue by Suvitruf** [OrbitzWorldwide/consul-client#61]
You are using `com.orbitz.consul.option.ImmutablePutOptions`, but there is no such class in `com.orbitz.consul.option` package. Did you forget to commit this file?

**Comment by Suvitruf** [comment]
Same for `ImmutableEventResponse` and etc.

**Comment by rickfast** [comment]
These classes are generated. Are you working with the source code?

**Comment by rickfast** [comment]
There are instructions in the read about the generated classes

**Comment by Suvitruf** [comment]
Yeh, I tried to add gen-tool to Eclipse project settings like mentioned here https://immutables.github.io/apt.html
But still can't compile library.

**Comment by gjesse** [comment]
Their instructions are a bit difficult to grok, but I was able to get ecplipse to compile by following the second part of the instructions -- enable annotation processing, then extend the M2_REPO variable to include the immutables annotation processor. One thing is that documentation is out of date in that it tells you the wrong jar to include - it should be org/immutables/value/2.0.16/value-2.0.16.jar. 

![extending M2_REPO](http://cl.ly/image/3F3G2X1h3J3h/Image%202015-09-07%20at%2010%3A28%3A52.png)

**Comment by Suvitruf** [comment]
@gjesse wow, thanks. Now it works )

**Comment by gjesse** [comment]
cool, i'll add this to the readme :)
