### ISSUE TITLE
Securing HTTP API calls with ACLs?

### ISSUE THREAD

**Issue by hotmeatballsoup** [OrbitzWorldwide/consul-client#64]
Admittedly I am a total Consul neophyte, so this request might not even make sense.

I'd like to enforce auth on my Consul server's exposed HTTP API. If I'm understanding the [security docs](https://www.consul.io/docs/internals/acl.html) correctly, their HTTP API can be secured by enforcing ACL policies. If that's the case, then I need to add/config those policies on the Consul servers, and then make sure that each HTTP request contains these "*ACL tokens*".

Doing a quick scan of the codebase here, I don't see any built-in support for ACL tokens. This leaves me thinking that either:
* I am completely misunderstanding the Consul security model; or
* There's a specific reason why you don't want this feature added to this lib; or
* It just hasn't been implemented yet (in which case, open to PRs?)

Thanks,
HMS

**Comment by rickfast** [comment]
Token request parameters were added to the HTTP API after this library was built.  Any method that accepts ```QueryOptions``` can take an ACL token.  Still needs to be added elsewhere.  PRs welcome!

**Comment by hotmeatballsoup** [comment]
I'm on it @rickfast - what are your general thoughts here? It seems that each `*Option` class extends `ParamAdder`, so perhaps move [`getToken()`](https://github.com/OrbitzWorldwide/consul-client/blob/master/src/main/java/com/orbitz/consul/option/QueryOptions.java#L21) up into the `ParamAdder` parent?

Correct me if I'm wrong here, but I think this *should* (famous last words) be as simple as giving HTTP client methods the ability to tack on an optional `?token=...` query string param.

**Comment by gjesse** [comment]
I have a few thoughts on this -- QueryOptions already will add the token to the query if specified, it shouldn't get pushed into ParamAdder. 

Most methods have a variation that takes QueryOptions already, for example  getValue(String key, QueryOptions queryOptions), so these can easily support tokens. 

However PutOptions and EventOptions used by KeyValue & EventClient respectively, do not supprt a token, so one should be added there as in QueryOptions. 

Additionally for full token support, an AclClient should be created to match the spec at https://www.consul.io/docs/agent/http/acl.html

**Comment by rickfast** [comment]
Only a handful of the endpoints accept the token query parameter.  We should probably figure out which ones need this functionality and go from there.

**Comment by hotmeatballsoup** [comment]
I'll review the endpoints and post back a list of those that I find as accepting token params, just to get things started.

@gjesse , I'm so new to Consul this is an embarrassing question, but how would we secure the ACL client itself?!? If the idea of adding token params to the other endpoints is to enforce authorization, then if we add a new ACL client (that can create its own ACL tokens!), it sounds like we'll need a way to make sure "normal" client can't actually use it. I'm not sure how this works outside of this Java client, perhaps the ACL endpoints require "master" tokens or something along those lines?

**Comment by gjesse** [comment]
@rickfast , You're right.. i thought i read somewhere that it was everywhere

>When the ACL system was launched in Consul 0.4, it was only possible to specify policies for the KV store. In Consul 0.5, ACL policies were extended to service registrations.

@hotmeatballsoup I just meant adding an AclClient class similar to KeyValueClient, HealthClient, etc. We don't need to do anything special about auth, but make sure these methods do support token use. It looks like from a brief reading of the docs that the methods there require a management token to work.

Honestly, if you are creating your tokens elsewhere and configuring them in your app, you could probably just make sure the existing endpoints support token use, and the full support could be added later.

**Comment by hotmeatballsoup** [comment]
Looks like there isn't great documentation on which endpoints currently support tokens. As of 0.5 all KV endpoints support it, and "some" agent endpoints support it. As of 0.6 this will be expanded to most of the other endpoints.

For now, it looks like there's no harm (from Consul's perspective) to send ACL tokens to *any* endpoint. Those endpoints that don't support them will just ignore them.

Anybody object to adding `QueryOptions` to all clients/endpoints?

**Comment by rickfast** [comment]
I'd rather not, just because it could be confusing to see the option to pass things like WAIT and INDEX to an unrelated endpoint.  That being said, I don't have a clean design idea off the top of my head (which is why I haven't just added something), so I'm open to whatever.

**Comment by hotmeatballsoup** [comment]
That's reasonable. How about this (so we can keep this moving forward):

* How about I take a stab at an `AclClient`; and
* I'll add optional `QueryOption` support for the KV/catalog endpoints that I need, in areas where I see it is missing

Then you guys can tell me how much my `AclClient` sucks (!), and the Orbitz client gains some additional `QueryOption` support, but without sprawling it all over the place, especially in areas where it doesn't make sense to add token params.

Thoughts? Hate mail?

**Comment by hotmeatballsoup** [comment]
And, if that sounds good, I'm not seeing any contribution guidelines in the README, so just let me know if there is anything specific I need to pay special attention to prior to submitting a PR (this is your baby, I'll happily oblige any requests).

**Comment by rickfast** [comment]
write tests, and don't make it hard for applications to upgrade :)

**Comment by hotmeatballsoup** [comment]
Will do!

Quick question: I forked and cloned locally and then ran `./gradlew clean build` and got a *ton* of errors all stemming from Gradle's inability to find all the Immutables-generated classes.

I've never worked with Immutables before, and never worked with annotation processors in Gradle. What's the Gradle invocation to build the consul-client from the command-line? Thanks!

**Comment by gjesse** [comment]
although the library is compiled for java6, you need at least java7 to do the annotation processing - the command you supplied should 'just work', for ide integration there are a few other steps (see the README), but i would suggest checking java -version first.

**Comment by hotmeatballsoup** [comment]
Ahh that's probably the issue. I'm on Java 8 locally, I'll see if I can force Gradle to use a Java 7 JDK...

**Comment by hotmeatballsoup** [comment]
@gjesse I added the following to `build.gradle` with the same results:

    sourceCompatibility = '1.7'
    targetCompatibility = '1.7'

As for actually specifying a non-default JDK in Gradle it looks like I could also add:

    compileJava.options.fork = true
    compileJava.options.forkOptions.executable = /path_to_javac

However I'm on a Mac, and [apparently it's not possible to have multiple JDKs on one machine](http://superuser.com/a/492303).

So either I need to figure out how to get the Gradle build running correctly on Java 8, or hopefully, the JDK version isn't the root issue and I'm just doing something silly here. Any other ideas? Are you positive `build` will invoke annotation processors without any special/additional config? Thanks again!

**Comment by gjesse** [comment]
java8 should be fine, that's what I use. Also on a mac, and use multiple
jdks by manipulating JAVA_HOME as needed, works fine.

>  Are you positive build will invoke annotation processors without any
special/additional config? Thanks again!

I am not a gradle expert at all, mostly I use maven -- that said, this is
what I found to be true, that I didn't have to specify any additional
config to build this.

**Comment by rickfast** [comment]
Can confirm the Gradle build doesn't require any special configuration

**Comment by hotmeatballsoup** [comment]
Sorry to be a pain here guys, but take a look at my [gist](https://gist.github.com/hotmeatballsoup/456ab8eb4c962bee9837). That's the output I get from running:

    ./gradle clean build > gradle-out.txt

...from the project root. These are (mostly) `ConnectionExceptions`...I have Consul installed locally (I can verify by the output of `consul -v`, but is Consul supposed to be running in some kind of special mode before I run the Gradle build?

**Comment by rickfast** [comment]
No worries, we appreciate your help.  Here's the exact commands that the Codeship build executes prior to building:

```
wget https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip --no-check-certificate
mkdir data
unzip 0.5.0_linux_amd64.zip
nohup ./consul agent -server -bootstrap -data-dir data &
```

Obviously you don't need to download consul each time.  Just nuke the ```data``` directory.

Let me know if that works.

**Comment by hotmeatballsoup** [comment]
Thanks @rickfast so I sort-of have this working now. If I open two terminals, and run consul from the first one (using the `consul agent -server -bootstrap -data-dir data` and excluding the `nohup` and trailing `&`), and run `./gradlew clean build` from the second one, I am now getting the build passing, but there are *many* warnings and 6 errors still complaining that it can't find the generated Immutables classes (which is puzzling because I would think Gradle would fail on compiler errors).

So it seems that the unit tests are passing (and I can confirm they are hitting the local consul instance by viewing  consul's stdout). But the annotation processor is not kicking in, or isn't processing anything. When I google "gradle annotation processors" I get dozens of results for *plugins* that claim to add annotation processing, which makes me feel like `./gradlew clean build` doesn't handle annotation processing out of the box. But clearly it works for you guys (!) so I'll keep digging in and will report back with any findings. Thanks again for the help here!

**Comment by JensRantil** [comment]
Hey, just stumbled across this issue today. I know I'm joining the discussion rather late, but wouldn't it make sense to also be able to set a global `token` for a `Consul` instance? It feels like the most common `token` usage is to set it once on application startup and then reuse it for the rest of the application life-cycle.

Or maybe there is already some kind of support to set default `QueryOptions` somewhere, perhaps? I'm new to `consul-client`.

**Comment by rickfast** [comment]
I thought about this. Are there use cases where you would need a different token for different API calls? If not, then I'm okay with this solution.

**Comment by hotmeatballsoup** [comment]
My only hesitation here is that, based on what I've read in the docs, there are essentially "management tokens" (used for things like the ACL service, and "user tokens" used for anything else. In this sense it may be desirable to have 2+ tokens per app instance.

**Comment by JensRantil** [comment]
@hotmeatballsoup AFAIK there are two types of ACL tokens; "managenent" and "client" (ref: https://www.consul.io/docs/internals/acl.html). However, I haven't seen anything hinting at Consul distinguishing between the two types in terms of API access. That is, we should be fine in terms of that.

> Are there use cases where you would need a different token for different API calls?

Probably. You could have a specific K/V scope only accessible to certain applications, while using a more general token for general K/V access.

**Comment by hotmeatballsoup** [comment]
@JensRantil sounds good!

Anybody else, I'm having a real tough time with Eclipse and Gradle generating the Immutables sources. Following the instructions on this project's README, when I go to extend the `M2_REPO` variable, I'm not seeing an "`immutables`" nor a "`org/immutables/value/2.0.16/value-2.0.16.jar`" in that dialog. Is there something I need to include elsewhere in Eclipse to make this available?
