### ISSUE TITLE
Missing fields for session creation

### ISSUE THREAD

**Issue by JensRantil** [OrbitzWorldwide/consul-client#66]
The [Consul documentation on sessions](https://www.consul.io/docs/agent/http/session.html#session_create) states that one can specify the following fields when creating a session:
```
{
  "LockDelay": "15s",
  "Name": "my-service-lock",
  "Node": "foobar",
  "Checks": ["a", "b", "c"],
  "Behavior": "release",
  "TTL": "0s"
}
```
Based on the methods on the `SessionClient`, it looks like only `Name` (parameter name `value` I assume is name) can be given. Let me know if I've missed something.

**Comment by rickfast** [comment]
For some reason, the session client takes JSON as a string. I haven't fixed it yet, and I wasn't very diligent when I reviewed the session client pull request. I can fix.

**Comment by JensRantil** [comment]
@rickfast Awesome. :+1:

**Comment by defucius** [comment]
Is there any progress on this addition? I also ran into an error when trying to read the session info by calling getSessionInfo(sessionId). The error seems to say the TTL value of "30s" cannot be demarshaled to a String?
>Caused by: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.orbitz.consul.model.session.ImmutableSessionInfo] value failed: argument type mismatch (through reference chain: Object[][0]->com.orbitz.consul.model.session.ImmutableSessionInfo["TTL"])
>
command line result:
> curl http://localhost:8500/v1/session/info/0de22989-9ad4-c5e5-b816-b2fdccde4336
[{"CreateIndex":13491,"ID":"0de22989-9ad4-c5e5-b816-b2fdccde4336","Name":"","Node":"agent-pro","Checks":["serfHealth"],"LockDelay":15000000000,"Behavior":"release","TTL":"30s"}]

**Comment by rickfast** [comment]
Orbitz has been in the process of integration with Expedia the past two weeks, and I've been mostly unable to code. I should be able to tackle this early next week. Sorry for the slowness. As always, PRs welcome.

**Comment by gjesse** [comment]
@rickfast , I was going to take a look at #70, but after checking out the existing code + this issue, it seems the lib would be better served by rewriting the session client. I may be able to put in some time on it this week, but I don't want to duplicate efforts as it's non-trivial. Are you still planning to work on this? want me to take a crack at it?

**Comment by rickfast** [comment]
I'm actually rewriting it as we speak. I wish I had looked harder at the pull request with this. Should be ready in just a bit.

**Comment by gjesse** [comment]
nice! i'll be happy to review it if u like

**Comment by rickfast** [comment]
Please: https://github.com/OrbitzWorldwide/consul-client/pull/71

**Comment by rickfast** [comment]
Fixed by edfdd46ee3edb453a0a08173ed56b35189fb8e33

**Comment by JensRantil** [comment]
Awesome! Do you think you could maybe make a release with this? :pray: ;)

**Comment by rickfast** [comment]
Yup. I'll do it first thing this morning

**Comment by JensRantil** [comment]
:heart:

**Comment by rickfast** [comment]
```0.9.11``` is available in jcenter and central

**Comment by JensRantil** [comment]
Sweet! Thanks!

**Comment by defucius** [comment]
Have anyone tried to set the session parameters with the new implementation? It seems that creating a session would fail with a 400 Bad Request if the ttl or lockDelay is set. Creating an empty session or a session with name as a single parameter works as in the test class. I haven’t tried the other three parameters.

This is with Maven build, ConsulAgent 0.9.11. My code looks like this:

Session sessionSettings = ImmutableSession.builder().lockDelay("30").build();
String sessionId = sessionClient.createSession(sessionSettings).getId();

The stack trace:

Exception in thread "main" javax.ws.rs.BadRequestException: HTTP 400 Bad Request
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:884)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:802)
	at org.glassfish.jersey.client.JerseyInvocation.access$600(JerseyInvocation.java:89)
	at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:673)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:421)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:669)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:414)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:296)
	at com.orbitz.consul.SessionClient.createSession(SessionClient.java:71)
	at com.orbitz.consul.SessionClient.createSession(SessionClient.java:52)

Did I miss anything in my code?

**Comment by rickfast** [comment]
Try ```"30s"```. Either way, I will add better tests and fix any issues. Thanks!

**Comment by defucius** [comment]
“30s” works. Thanks!

**Comment by JensRantil** [comment]
@rickfast I assume Consul returns some kind of error message on that 400. Would it make sense to try to parse the 400 error page and include it in the exception? Would make debugging errors like @defucius's much easier. Just an idea...

**Comment by rickfast** [comment]
Yeah, I can add this

**Comment by JensRantil** [comment]
:+1:
