### ISSUE TITLE
Renew session always returns true

### ISSUE THREAD

**Issue by shanielh** [OrbitzWorldwide/consul-client#70]
Even when session doesn't exists and the response was 404.

**Comment by rickfast** [comment]
I'm reworking the Session stuff this morning. I'll make sure this works properly

**Comment by rickfast** [comment]
Fixed with https://github.com/OrbitzWorldwide/consul-client/pull/71

**Comment by rickfast** [comment]
Change is on master (edfdd46ee3edb453a0a08173ed56b35189fb8e33). I will release ```0.9.11``` tomorrow with the fixes
