### ISSUE TITLE
General question about popular integration patterns for service registration in consul

### ISSUE THREAD

**Issue by sid-saddala** [OrbitzWorldwide/consul-client#72]
I apologize upfront If this is not the right forum to ask about this. 
Wanted to know popular patterns how developers are using this Orbitz's consul-client library for simple service registration/discovery?

When a producer creates a new service, should they use AgentClient.register() and also KeyValueClient. putValue(k,v) to complete registration? Are both required? (Here key being the service name and value being the actual endpoint)
When consumers want to discover this new service, would they just use KeyValueClient. getValue(k)?

**Comment by rickfast** [comment]
Hi - KV client is not needed for service registration. The typical pattern is for a service to register itself using ```AgentClient``` and for client services to discover registered instances using ```HealthClient.getHealthyServiceInstances```. I can make a gist sometime this week as an example

**Comment by sid-saddala** [comment]
@rickfast That would be great.

**Comment by gjesse** [comment]
there is an example you could follow for service discovery in the README

```java

Agent agent = client.agentClient().getAgent();
String serviceName = "my-service";

ServiceHealthCache svHealth = ServiceHealthCache.newCache(healthClient, serviceName);

svHealth.addListener(new ConsulCache.Listener<HostAndPort, ServiceHealth>() {
    @Override
    public void notify(Map<HostAndPort, ServiceHealth> newValues) {
        // do Something with updated server map
    }
});
svHealth.start();

```

**Comment by rickfast** [comment]
Here's a very simple, untested gist
https://gist.github.com/rickfast/5fd290fcf0a04f07d466

**Comment by sid-saddala** [comment]
@rickfast Thanks much. I am closing the issue.
