### ISSUE TITLE
SSL/TLS support

### ISSUE THREAD

**Issue by JesperTerkelsen** [OrbitzWorldwide/consul-client#73]
Currently its not possible to use this java client against a consul server with SSL enabled. 
Or even specify the ``https`` protocol.

**Comment by rickfast** [comment]
I'll add the ability to provide an ```SslContext```. You can specify https if you supply a raw url as a string.

**Comment by rickfast** [comment]
Via 1599099f64a519d4d7fa7d38405f300a87b65e59 you can do something like this:

```java
SSLContext context = SSLContext.getInstance("TLSv1");
TrustManager[] trustManagerArray = {
    NullX509TrustManager.INSTANCE
};

context.init(null, trustManagerArray, null);

Consul.builder().withUrl("https://your-secure-host:8500").withSslContext(sslContext).build();
```

**Comment by JesperTerkelsen** [comment]
:+1: Nice this is just what i need!

**Comment by jadams74** [comment]
Why a Null trust manager here? Doesn't this undo cert verification/validation?

**Comment by rickfast** [comment]
yes, but the point of the comment wasn't to explain how Java SSL contexts work, it was to show how to provide it to the API

**Comment by jadams74** [comment]
roger, just hope noone c&p that snippet ;)
