### ISSUE TITLE
Inconsistency between expected jackson deserialized collections classes and immutable collections in generated classes.

### ISSUE THREAD

**Issue by tolwi** [OrbitzWorldwide/consul-client#78]
f.e. 

`ServiceHealth`:

`
@JsonDeserialize(as = ArrayList.class, contentAs = HealthCheck.class)
public abstract List<HealthCheck> getChecks();
`

but in generated `ImmutableServiceHealth`:

`public ImmutableList<HealthCheck> getChecks() {..}`

To reproduce - just update all jackson dependencies to 2.6.3 and run tests.

**Comment by rickfast** [comment]
I'll upgrade and get this fixed.  Thanks!

**Comment by rickfast** [comment]
fixed by ac86124866c7c0f324d26707c4c30d5d43162802

**Comment by rickfast** [comment]
this fix is available now in ```0.9.14```
