### ISSUE TITLE
com.orbitz.consul.option.QueryOptionsBuilder missing

### ISSUE THREAD

**Issue by nickspat** [OrbitzWorldwide/consul-client#79]
As per your documentation for blocking query, com.orbitz.consul.option.QueryOptionsBuilder needs to be passed. I don't see that anywhere in any of the packages.

**Comment by gjesse** [comment]
This was my bad, i didn't update those docs with the new style.

**Comment by nickspat** [comment]
I am still waiting for some working example or documentation update. I tried using KeyValueTests.testGetValuesAsync() , but i dont see a callback getting invoked.

**Comment by gjesse** [comment]
you can take a look at https://github.com/gjesse/consul-client/commit/bbec378fc0bedeea20e2e0c716c31838131c6b91

**Comment by nickspat** [comment]
Yep that worked with 1 minor change in the code. I have submitted the pull request.
