### ISSUE TITLE
Consul Cache

### ISSUE THREAD

**Issue by amitgilad3** [OrbitzWorldwide/consul-client#81]
Hi ,
I am trying to use consul cache and i keep getting the following error : 
 ERROR com.orbitz.consul.cache.ConsulCache - Error getting response from consul. will retry in 10 SECONDS

why do i get this error??

code example:
    LOGGER.info("Initializing consul cache!!!!!");
        com.orbitz.consul.Consul consul =  com.orbitz.consul.Consul.builder().build();
        KeyValueClient kvClient = consul.keyValueClient();

        kvCache = KVCache.newCache(
                kvClient, applicationName, watchTimeout
        );
        kvCache.start();

        if (!kvCache.awaitInitialized(10, TimeUnit.SECONDS)) {
            LOGGER.error("Failed to listen to reportservice in consul");
        }
        kvCache.addListener(consulCacheListener);
        LOGGER.info(" consul cache Initialized !!!!!");

**Comment by rickfast** [comment]
The Consul Client throws a ```TimeoutException``` when 10 seconds is up and no data is returned and the failure callback is executed. Likely, there's no problem. It's just a misleading log message.

**Comment by dimagol1989** [comment]
It is a problem. every TimeoutException we have a printing to log, and kvClient.getValues method is executed again. so the watchTimeout(KVCache argument) is useless.

The exception caused from using:
'org.apache.cxf:cxf-rt-rs-client:3.0.3'
'org.apache.cxf:cxf-rt-transports-http-hc:3.0.3'

solve this in my program by switching to:
'org.glassfish.jersey.core:jersey-client:2.22.1'
'javax.ws.rs:javax.ws.rs-api:2.0.1'

BUT! when initializing KVCache, the watchTimeout is limited up to 10m.
https://www.consul.io/docs/agent/http.html (Blocking Queries)

**Comment by xiaogaozi** [comment]
The latest consul-client has use OkHttp now, so if you encounter this situation, you could make read timeout longer use `Consul.Builder.withReadTimeoutMillis()`. If you don't, OkHttp [default](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/OkHttpClient.java#L482) set read timeout to 10 seconds.

```java
Consul consul = Consul.builder()
        .withReadTimeoutMillis(60 * 1000)  // 60 seconds
        .build();
```
