### ISSUE TITLE
Jackson 2.5 <--> 2.6 interoperability?

### ISSUE THREAD

**Issue by jhovell** [OrbitzWorldwide/consul-client#90]
@rickfast I was wondering if you knew why you needed to change KVCache in the following commit. I have a few JEE apps that are stuck on Jackson 2.5.3, and even if I include the corresponding jackson-datatype-guava 2.5.3, I run into an issue where the first 2 letters of my KV keys are clipped. Seems like you maybe experienced the same thing since this line of code changed with the upgrade:

```
return input.getKey().substring(rootPath.length() + 1);
```

Any idea why? Seems strange that a Jackson upgrade would affect this. It's possible for me to exclude Jackson 2.5 from the JEE run time and roll/bring my own, but it seems really heavy-handed & thought something else might be amiss. 

https://github.com/OrbitzWorldwide/consul-client/commit/ac86124866c7c0f324d26707c4c30d5d43162802

**Comment by rickfast** [comment]
IIRC, the substring thing was just a fix for another pull request that broke functionality. I just piggy backed it on the jackson changes.
