### ISSUE TITLE
Leverage Retrofit

### ISSUE THREAD

**Issue by nrshrivatsan** [OrbitzWorldwide/consul-client#94]
Hi friends,

Your Consul-client is a life-saver.

Just a suggestion. 

We found you using [Jersey ReST Client](https://github.com/OrbitzWorldwide/consul-client/blob/master/src/main/java/com/orbitz/consul/KeyValueClient.java#L16). 

[```Retrofit```](http://square.github.io/retrofit/) reduces lines of code and is simple to use. 

IFF you choose to , please use version ```2.0.0-beta3+```

**Comment by rickfast** [comment]
Thanks! We're discussing Retrofit in issue #93
