### ISSUE TITLE
Prepared Query support in consul-client

### ISSUE THREAD

**Issue by justinjose28** [OrbitzWorldwide/consul-client#95]
I couldn't find anything related to  [Prepared Queries](https://www.consul.io/docs/agent/http/query.html) in the client. Any plans to support this?

**Comment by rickfast** [comment]
@justinjose28 yes! Just need to find the time! I'll mark this as help wanted and try to find time to take a crack at this

**Comment by rickfast** [comment]
Resolved by 88e7abb4492410ca110289293e830303287964dd
