### ISSUE TITLE
Events doesn't filtered by name

### ISSUE THREAD

**Issue by sharpyfox** [OrbitzWorldwide/consul-client#99]
Hello. I use `0.9.16` version from maven. Seems that event list doesn't requested properly (filtered by name). Snippet to reproduce:

```
eventClient.listEvents("name-to-filter");
```

Actual query was made: `GET /v1/event/list`, however I expect that `/v1/event/list?name=name-to-filter` will be called.

**Comment by rickfast** [comment]
Fixed by 3198b3a7c8bf92aa728064adac2582141b89d746. I'll release a new version tomorrow.

**Comment by sharpyfox** [comment]
Thanks!

**Comment by rickfast** [comment]
release in ```0.10.0```
